#!/usr/bin/env bash
# prints Best school 10X using while and add if i = 4 bad luck and good luck for 8.
i=1
while ((i < 11)); do
    if [ $i -eq 4 ]; then
	echo "bad luck";
    elif [ $i -eq 8 ]; then
	echo "good luck";
    else
	echo "Best School";
    fi
    ((i++));

done
